{
 "title": "lab4",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU Usage",
     "type": "timeseries",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total[5m]) * 1000)",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "timeseries",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "process_open_fds", "legendFormat": "Open FD" }
     ]
    }
   ]
  },
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime Postgres",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_postmaster_start_time_seconds * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_statements_total_time_seconds)/sum(pg_stat_statements_calls)",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Number of mistakes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 10, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_xact_rollback)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transactions per second",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_database_xact_rollback[1m])) + sum(rate(pg_stat_database_xact_commit[1m])))/60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_calls[1m]))/60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of active autovacuum processes",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "pg_stat_activity_autovacuum_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Longest Transaction",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "pg_stat_activity_max_tx_duration >= 0",
       "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Top 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOP-5 Most long-running queries by mean_time second",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 210 },
     "targets": [
      {
       "expr": "topk(5, pg_stat_statements_mean_time_seconds)"
      }
     ]
    },
    {
     "title": "TOP-5 Most called queries",
     "type": "table",
     "gridPos": { "h": 6, "w": 10, "x": 11, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, pg_stat_statements_calls)"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "stat",
     "description": "Connected sessions, including Postgres internal processes like Autovacuum. < 1 Warn / > 300 Error thresholds by default",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"active\"})"
      }
     ]
    },
    {
     "title": "% current/total connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(pg_stat_activity_count) / sum(pg_settings_max_connections)) * 100",
       "legendFormat": "total/all connection"
      }
     ]
    },
    {
     "title": "Mean query time avg 1m ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_mean_time_seconds[1m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Total queries count (1m rate)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_calls[1m])) by (datname) ",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Tuples inserts/updates/deletes",
     "type": "timeseries",
     "description": "Source: pg_stat_database",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum((rate(pg_stat_database_tup_inserted[10m])))",
       "legendFormat": "Inserts"
      },
      {
       "expr": "sum((rate(pg_stat_database_tup_updated[10m])))",
       "legendFormat": "Updates"
      },
      {
       "expr": "sum((rate(pg_stat_database_tup_deleted[10m])))",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "Read Stats",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_fetched[10m]) > 100",
       "legendFormat": "{{datname}} SELECT (index scan)"
      },
      {
       "expr": "rate(pg_stat_database_tup_returned[10m]) > 100",
       "legendFormat": "{{datname}} SELECT (table scan)"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "description": "1 Minute rate of transactions committed or rollback.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum ((rate(pg_stat_database_xact_commit[10m])))",
       "legendFormat": "committed"
      },
      {
       "expr": "sum ((rate(pg_stat_database_xact_rollback[10m])))",
       "legendFormat": "rollback"
      }
     ]
    },
    {
     "title": "I/O Read/Write time",
     "type": "timeseries",
     "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum ((rate(pg_stat_database_blk_read_time[10m])))",
       "legendFormat": "blk_read_time"
      },
      {
       "expr": "sum ((rate(pg_stat_database_blk_write_time[10m])))",
       "legendFormat": "blk_read_time"
      }
     ]
    }
   ]
  },
  {
   "title": "some_stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{datname=\"postgres\"} / (pg_stat_database_blks_read{datname=\"postgres\"} + pg_stat_database_blks_hit{datname=\"postgres\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 11, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 19, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated)"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 19, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted)"
      }
     ]
    },
    {
     "title": "Current fetch data",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 19, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched)"
      }
     ]
    },
    {
     "title": "Database size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_database_size{datname=\"postgres\"}",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Replication Lag (Only for Replica)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "rate(pg_replication_lag[5h])", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    }
   ]
  },
  {
   "title": "Conflicts & Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": " Conflicts/Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "conflicts",
       "expr": "sum(rate(pg_stat_database_deadlocks[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "deadlocks",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "conflicts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "deadlocks",
       "expr": "sum(rate(pg_stat_database_conflicts[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "conflicts",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "deadlocks" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Lock Tables",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "pg_locks_count  > 0",
       "legendFormat": "{{datname}} {{mode}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_static", "legendFormat": "{{short_version}}" }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_random_page_cost" }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_work_mem_bytes" }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_max_wal_size_bytes" }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_settings_max_connections" }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_seq_page_cost" }
   ]
  }
 ]
}